### ISSUE TITLE
ChirpStack Device 등록 방법

### ISSUE THREAD

**Issue by qaw302** [GN-TA/study#5]
## Device-profile template
Network Server > Device Profile Templates
![Image](https://github.com/user-attachments/assets/7601edea-7463-4fad-9cc7-322f26f4cbfc)

- 사전 정의된 템플릿
- 특정 장치나 제조사에 맞춘 설정값

- 아래 페이지에 나온 설명에 따라 미리 vendor 별 정의된 템플릿을 적용할 수 있음
    
    https://www.chirpstack.io/docs/chirpstack/use/device-profile-templates.html
    
    - docker에서 적용방법
    ```
    docker exec -it --user root chirpstack /bin/sh
    / # apk update
    / # apk add git
    / # git clone https://github.com/brocaar/lorawan-devices /opt/lorawan-devices
    / # chirpstack -c /etc/chirpstack import-legacy-lorawan-devices-repository -d /opt/lorawan-devices
    ```
    

- 적용한 템플릿은 Device Profile을 등록할때 사용하면 됨

## Device Profile
Tenant > Device Profile
![Image](https://github.com/user-attachments/assets/be8af72d-6dd5-4c6c-b4ca-8cb52163a414)

- 디바이스 정보를 등록
- device profile templates에 등록되어있는 template을 선택하여 빠르게 등록가능
- 등록할 디바이스가 어떻게 동작할지를 정함

### General

- **Name** : 모델명-join방식 형태로 보통 등록하는 중
- **Firmware version** : 펌웨어 버전은 보통 장치 정보에 나와있음
    
    milesight의 경우 Milesight ToolBox 어플 다운 받고 장치 인식해서 정보 확인 가능
    
- **Region** : 지역별 주파수 대역
- **MAC version** : LoRaWAN MAC version.
    
    이것도 milesight의 경우 어플에서 확인 가능 (보통 1.0.3인듯)
    
- **ADR algorithm** : 에너지 효율성 극대화하기 위해 데이터 전송 속도(DR)와 출력전력을 동적으로 조정하는 기능
    
    (에너지 효율, 최적화 . .)
    

### Join (OTAA / ABP)

- **OTAA (Over-The-Air Activation), ABP (Activation By Personalization)**
    
    LoRaWAN 장치가 네트워크 연결될 때 사용하는 인증 방식
    
    데이터를 주고 받을 때 암호화와 복호화가 필요
    
    이때 사용되는 키가 Session Key
    
    LoRaWAN에서는 NwkSKey, AppSKey 두가지가 있음
    
    - NwkSKey : 네트워크 서버에서 해당 키를 사용해 패킷 무결성 확인 (데이터 손실안됐나. . )
    - AppSKey : 애플리케이션 서버에서 해당 키를 사용해 데이터를 복호화하여 사용
    
    - OTAA
        
        네트워크 서버에서 NwkSKey, AppSKey를 발급해줌
        
        동작 방식
        
        1. 장치가 네트워크 서버로 Join Request(DevEUI, AppEUI 등을 포함) 전송
        2. 네트워크 서버에서 Join Accept(NwkSKey, AppSKey를 포함) 메시지를 장치로 전송
        3. 장치는 전송받은 세션키로 암호화된 통신 시작
        
        장치 재시작, 재부팅시 다시 Join Request를 보내 재가입해야하는 특징
        
        보안성이 높음
        
        네트워크 변경에도 쉽게 새로 연결 가능
        
        가입 절차에 추가 전력을 사용하긴 하지만 이후에는 정상적인 전력 소비
        
    
    - ABP
        
        장치에 미리 정의된 세션키를 사용하여 네트워크 장치에 연결하는 방식
        
        1. 미리 정의된 세션키가 네트워크 서버에 설정이 되어있어야함
        2. 별도의 Join Request를 보내지 않고 정의된 세션키를 이용하여 바로 통신 시작
        
        가입 절차가 없어서 전력소모가 적음 + 빠른 연결
        

## add device
Tenant > Applications > [application] > Add device
![Image](https://github.com/user-attachments/assets/3549cb1f-536e-46f6-8e5b-000c024fdae9)

- 실제 장치를 등록
- **Name** : ‘모델명-DevEUI후반번호’ 형태로 등록중
- **DevEUI** : 장치에 정의된 고유번호
- **Device Profile** : 등록되어있는 장치 정보를 선택하여 사용
- **Device 등록후 session key 등록**
    - OTAA
        - Milesight 장치의 경우
            
            Milesight IoT Cloud 어플에서 장치를 스캔하면 나오는 Application Key을 넣어주면됨

> 만약 device 를 지우고 다시 등록할 경우 OTAA 방식은 device를 재부팅 해줘야 다시 연결이 된다

**Comment by caboooom** [comment]
![Image](https://github.com/user-attachments/assets/0d878295-cae5-4891-99b5-f982371bb88d)
